### ISSUE TITLE
Maßnahmen zur besseren Partizipation beim Lama-Treffen finden und ins Lama-Treffen einbringen

### ISSUE THREAD

**Issue by metzgaria** [serlo/u_neue-standorte#12]
Vorschlag: two paragraphs

**Comment by kulla** [comment]
@metzgaria Unter https://docs.google.com/document/d/1y4FDZ4bqhAbO2qxBjW5SQ8xZUon0KSmsndu29JfvOeg/edit# habe ich ein Dokument aufgesetzt, wo Vorschläge zur Verbesserungen gesammelt werden können. Wenn wir dieses ausreichend ausgearbeitet haben, können wir dies in das Lama-Treffen einbringen.

**Comment by kulla** [comment]
Im Dokument https://docs.google.com/document/d/1y4FDZ4bqhAbO2qxBjW5SQ8xZUon0KSmsndu29JfvOeg/edit# habe ich die Ergebnisse festgehalten (Welche Maßnahmen wurden getroffen? / Welche Maßnahmen bleiben aus welchen Gründen im Backlog).
