### ISSUE TITLE
Infrastruktur für Konferenzcalls verbessern

### ISSUE THREAD

**Issue by metzgaria** [serlo/u_neue-standorte#15]
-neues kommunikationstool
-soundoptimierung

**Comment by kulla** [comment]
Protokoll (aus einem Gespräch):

* Es gibt kaum ein freies Konferenztool, welches wir nicht schon probiert haben.
* Viele Probleme können nicht behoben werden (wie schlechte Internetverbindung)
* Andere Konferenz-Lösungen sind teuer

Bisher umgesetzt:

* Remote-Moderator*innen funktionieren ganz gut

Aktuell weitere Möglichkeiten:

* Konferenztelefon.
* Einige Abstimmungen können schriftlich abgebildet werden / Remote-Arbeiten vermeiden.
* Anderes Mikro testen.
