### ISSUE TITLE
Textvorlagen für Facebookposts und Rundmails erstellen

### ISSUE THREAD

**Issue by OleGaertner** [serlo/u_neue-standorte#17]
Siehe Dokument für E-Mail und Facbook-Gruppen Vorlagen: https://docs.google.com/document/d/1ZNGpEwzM89B-Q5K93NiQgUOo468naZ37FvuibmgyaFA/edit

**Comment by kulla** [comment]
Dokument für E-Mail und Facbook-Gruppen Vorlagen: https://docs.google.com/document/d/1ZNGpEwzM89B-Q5K93NiQgUOo468naZ37FvuibmgyaFA/edit

**Comment by jakobwes** [comment]
Wird das approved? Dann würde ich das als done kennzeichnen @kulla

**Comment by kulla** [comment]
@jakobwes Ich habe gerade mit @metzgaria gesprochen. Sie wird bei diesem Task helfen. Grundlegend sehe ich, dass die Texte noch verbessert und gekürzt werden müssen. Auch sollte man sich etwas überlegen, dass nicht alle Texte gleich sind. (Entschuldige die späte Antwort – hatte viel mit der Uni zu tun)

**Comment by kulla** [comment]
@metzgaria Habe gerade mit @jakobwes gesprochen. Die nächsten Wochen ist er stark mit Uni eingebunden und hat für diesen Task keine Zeit. Dank dir für das Übernehmen des Tasks! :-)
