### ISSUE TITLE
Ansprechpersonen finden

### ISSUE THREAD

**Issue by metzgaria** [serlo/u_neue-standorte#25]
Beschreibung: Wie kann man Ansprechpersonen in der Community und im Serlo Team finden? Wie soll man vorgehen, wenn man Fragen in anderen Bereichen hat?

**Comment by kulla** [comment]
An folgende Ansprechpersonen habe ich gerade gedacht:

* Organisation von Veranstaltungen: Kathi
* Ansprache / Gewinnung von Personen: Mellie
* Standorte-Fragen: Kulla
* Sonstiges: de@serlo.org

@Standorte: Zu welchen anderen Themen habt ihr in den letzten Monaten Ansprechpersonen bei Serlo gesucht? Welche Ergänzungen fallen euch in der Liste ein?

**Comment by kulla** [comment]
Standorte-Call:

* Kooperationen / Zusammenarbeit / Partnerschaften
* Ansprechpartner für eine Unit
* Ansprechpartner für inhaltliches Fach (-> besteht noch Diskussionsbedarf)
