### ISSUE TITLE
Best Practices / Erfahrungen in der Standorteorga und -aufbau sammeln (z.B. Community-Betreuung)

### ISSUE THREAD

**Issue by metzgaria** [serlo/u_neue-standorte#26]
In einem Supportdokument werden folgende Fragen beantwortet:

* Wie werden Community-Mitglieder in den Standorten am Besten betreut?
* Wie soll in den Standorten Community-Mitglieder gewonnen werden?

Zusätzlich werden Erfahrungen in der Standorte-Orga und -Aufbau gesammelt (kurz und prägnant)

**Comment by kulla** [comment]
Ursprünglich gab es die folgenden zwei Fragen für unsere Unit:

* Wie werden Community-Mitglieder in den Standorten betreut?
* Wie soll in den Standorten Community-Mitglieder gewonnen werden?

Jedoch darf hier nach mein Verständnis jeder Standort seine eigene Antwort auf obige Fragen finden. Obige Fragen liegen sogar im Verantwortungsbereich jedes einzelnen Standorts. Wir sollten aber die Standorte in der Beantwortung dieser Fragen unterstützen (wenn gewünscht). Ein Best-Practice-Guide ist hier eine gute erste Maßnahme.

**Comment by kulla** [comment]
Hauptdokument: https://docs.google.com/document/d/1GGS1e5zZw5GrM51Khe_frVycsOkDCRKcV64gZ7YjmfY/edit
