### ISSUE TITLE
Teammitglieder des Standorts in das Team auf Github einladen

### ISSUE THREAD

**Issue by kulla** [serlo/u_neue-standorte#38]
Folgende Personen sollen in das Team [U Neue Standorte](https://github.com/orgs/serlo-org/teams/u-neue-standorte/members) eingeladen werden:

- [x] https://github.com/jakobwes
- [x] https://github.com/MenujaMS

Es fehlen die restlichen Personen der Unit.

**Comment by kathongi** [comment]
Einmal in die Gruppe aufnehmen bitte :)

**Comment by kulla** [comment]
Done. Alle Personen, die Zugriff auf das Team angefragt haben, wurden eingeladen. Bei Wunsch kann in Zukunft weitere Zugriffe vergeben werden. Einfach bei mir melden.
