### ISSUE TITLE
Kommunikation für die Standorte verbessern

### ISSUE THREAD

**Issue by kulla** [serlo/u_neue-standorte#40]
Die Kommunikation für die Standorte soll verbessert werden. Folgende Erfahrungen haben die Personen in den Standorten bisher gemacht (Protokoll aus einem Standorte-Call):

* Problem des Umzugs
* Slack: Subthreads gehen unter -> ein Nachteil
* Gedanke an ein selbstgehostetes System ist schön, wenn Kapazitäten da sind
-> Discord verbessern, wenn Kapazitäten für Serlo-Chat nicht da sind
* M: Discord ohne Threading funktioniert nicht, bei vielen 
* T: Discord eher nicht -> Slack hat kein Voice-Chat
* M: Viel Noise / Bei Slack müsste man aktiv Threads anklicken / Umzug gerade nicht
-> Wenn dann jetzt Slack oder jetzt selbstgehostet
-> GitHub: Nicht verständlich für nicht Informatiker -> Verständlichkeit für Geisteswissenschaftler (Slack ist da gut und intuitiv)
* C: Hürde bei neuen Netzwerken anmelden / Leute schauen wenig rein
* M: Slack besser
* N: Hosting -> wichtig, dass selbst gehostet
* Slack: Ping-Funktion ist gut
* Wenn Umzug: Lohnt sich Verbesserung von Discord?
* N: keine guten Erfahrungen mit jit.si

Featurewünsche an das Kommunikationstool

* Threads
** Notification für Subthreads (Opt-in)
* Voice-Chat (für Konferenzen)
* App
* Channel-Logik
* Wenn Umzug: Ein überlegter Umzug / sehr langsam rangehen
* Tabs, die nebeneinander offen sind (integriert auf einer Seite)
-> Kompromiss: Chat sollte viel leichter zu finden sein
* Integration von Projektmanagementtools (Updates / Aufgaben referenzieren / Artikel referenzieren)
* Datenschutz
* Anmeldung mit Invite-Link
* Hosting-Aufwand
* Benutzerfreundlichkeit
* API / Botintegration
* Unread-Funktionalität / Reminder / Umwandlung eines Kommentars in ein ToDo

**Comment by kulla** [comment]
Dokument zu diesem Task: https://docs.google.com/document/d/1GWHDn9OWGPF0nMrC-Wdf6zwHc3VbRboXpY1mITfywVg/edit

**Comment by metzgaria** [comment]
zusätzlich: wie ist es für Leute ohne serlo.org-Account?, Rollen-> “Quasi Tags”, Broadcast ähnlich zu Whatsapp, Channel verlinken, freier Community-Kalender , Onboarding-Nachrichtenserie

**Comment by kulla** [comment]
Info: Aktuell kümmert sich Nish aus der Begleitungs-Unit darum...
