### ISSUE TITLE
Asynchronen Entscheidungsprozess für die Community finden

### ISSUE THREAD

**Issue by kulla** [serlo/u_neue-standorte#42]
Es gibt aktuell zwei Wege der Entscheidungen in den Communitys (für communityweite Themen):

* Redaktionsplanning (fachdidaktische Themen)
* Standorte-Call (standortespezifische Themen)

Nun werden nicht alle Community-Mitglieder zu diesen Treffen (die aktuell alle vier Monate angesetzt sind) anwesend sein können. Es ist also notwendig, diese Entscheidungsprozesse durch ein asynchrones Entscheidungsprozess zu ergänzen. Wie sollen diese stattfinden?

**Comment by kulla** [comment]
Eine Möglichkeit: [Prozess der Meinungsbilder](https://de.wikipedia.org/wiki/Wikipedia:Meinungsbilder) bei der deutschsprachigen Wikipedia.

**Comment by jakobwes** [comment]
Dieser Prozess ist eine gute Idee. Ansonsten ist mein Eindruck aber auch, dass es in der Community an mehreren weiteren stellen noch Entscheidungsgremien und Entscheidungen gibt, nämlich sowohl innerhalb der Standorte und deren communitys, in den Treffen, als auch innerhalb der einzelnen Fächer. Zusätzlich zu diesem Prozess könnte man solche Entscheidungsorte auch "offizieller" machen. Diese könnten sich unter Umständen konkreteren Themen widmen, während dann für übergreifende didaktische und allgemeine Initiativen so ein Prozess verankert wird.

**Comment by kulla** [comment]
@jakobwes Guter Punkt. Ich habe in der Aufgabenbeschreibung ergänzt, dass es mir hier nur um Entscheidungsprozesse für communityweite Themen handelt (z.B. allgemeine Artikelrichtlinien). Wie du richtig beschrieben hast, haben Standorte und ihre Fächer eigene Entscheidungsprozesse und nach dem Subsidiaritätsprinzip sollen / müssen sie für ihre speziellen Themen eigene Entscheidungsprozesse finden.

Ich denke, wir können auch einfach mal schauen, welche Entscheidungsprozesse sich in der Community herausbilden. Diejenigen, die sich als erfolgreich herausstellen, kann man als Grundlage für Entscheidungsprozesse heranziehen.

**Comment by kulla** [comment]
Habe einen Vorschlag für ein "Best Practise" als Thema für das nächste Redaktionsplanning vormuliert: https://docs.google.com/document/d/1a8qn0vF3dR_EhdmY72bOpD_lQ2QLxdEKZguLPZtAfO0/edit

Nach diesem Prinzip laufen aktuell Vorschläge bei uns in der Unit auf Slack. Todos:

- [x] Feedback am Wochenende an den Redaktionstagen erfragen

**Comment by kulla** [comment]
Lösung wurde im Redaktionsplanning besprochen und ist nun auf Discord in `#welcome` beschrieben.
