### ISSUE TITLE
Ansprechpersonen in Serlo-Standorteseiten aufnehmen

### ISSUE THREAD

**Issue by kulla** [serlo/u_neue-standorte#44]

**Comment by kulla** [comment]
Aktuelle Idee:

de@serlo.org als Kontaktadresse für alle Anfragen der Community. Dies ist für die Community die einfachste Lösung (sie muss nicht wissen, wer aktuell bei Serlo für was zuständig ist). Die Mails werden dann an die richtigen Personen weitergeleitet.

Todos:

- [ ] Lösung mit Verantwortlichen von de@serlo.org besprechen
- [ ] Feedback für diese Lösung einholen

**Comment by jakobwes** [comment]
Finde ich sehr gut. Macht die Wikimedia auch ähnlich. Aber es sollte sichergestellt werden, dass die E-Mails sehr schnell weitergeleitet und beantwortet werden. 
Gleichzeitig hat dieser Task aber für mich auch eine doppelte Konnotation: dass es nämlich nicht nur um - wichtige - Ansprechpersonen für die Community geht, sondern auch um welche für die Standorte (d.h. für Standorteverantwortliche und engagierte Mitglieder der Standorte). Für die sollte sichergestellt werden, dass sie wissen an wen sie sich wenden müssen/können bei Fragen und deren Anfragen (die ja quasi teamintern sind) direkt weitergehen: z.B. der Fall: ein Community-Mitglied will in der Programmierung mitarbeiten: an wen wendet die betreuende Perosn im Standort sich da/wer ist die Ansprechperson/wer ist verantwortlich für Betreuung, Anfragen und wem kann die Person schreiben um zu fragen, ob es Kapazitäten gibt, wer aus München oder sonstwo kümmert sich um die Betreuung, Aufgaben, Einbindung? Oder alternativ ein Standortemitglied will etwas machen, das die Belange einer unit, einer bestimmten Gruppe, Redaktionsgruppe,... tangieren könnte.  Für all diese Fragen müssten Ansprechpersonen aus München,... da sein, die sich dazu bereit erklären und die man fragen kann. Dazu kommt auch noch der Fall, dass die meisten Anfragen der Community in den Standorten auch direkt - weil der Kontakt unmittelbarer ist - an die Standorte gehen dürften. Also müssten auch dazu und für alle weitergehenden Belange, orgafragen,... Verantwortliche bereitstehen.
