### ISSUE TITLE
Recherche zur Standortverwaltung bei anderen Organisationen

### ISSUE THREAD

**Issue by metzgaria** [serlo/u_neue-standorte#5]

**Comment by metzgaria** [comment]
könnte mal die imagine-alumni gruppe anzapfen

**Comment by kulla** [comment]
Hier die Beschreibung, wie sich die jDPG Standorte organisieren: https://www.dpg-physik.de/dpg/gliederung/junge/mv2018/mv/dokumente/GO_2017.pdf
