### ISSUE TITLE
Feature-Wünsche: Kontaktverwaltung für die Community

### ISSUE THREAD

**Issue by kulla** [serlo/u_neue-standorte#52]
Für die Community benötigen wir eine Kontaktverwaltung, damit Standorte und die alle Fachbereiche die Kontaktdaten ihrer Mitglieder verwalten können. Zusätzlich könnte diese Kontaktverwaltung für die Kommunikation mit und unter der Community genutzt werden.

Dieser Task sammelt sie Feature-Wünsche an eine solche Kontaktverwaltung.

**Comment by Claudia4** [comment]
Ich wünsche mir
* Zugänglichkeit von Benutzernamen (für Serlo.org, Wikibooks, Discord) und Namen für alle Autor*innen (um mehr Kommunikation innerhalb der Community ermöglichen)
* Zugänglichkeit von Kontaktdaten wie Mail, Handynr. für Teammitglieder

**Comment by kulla** [comment]
Meine Ideen:

* automatische Erstellung von Mail-Verteiler aufgrund der Kontaktverwaltung
* Nutzung für Statistiken (welche redaktionellen Expertisen stecken in welchen Standort)
* Generierung der Standorte-Seiten damit / helfen die Standortemitglieder auf den Standorte-Seiten automatisch zu listen
* Community verwaltet ihre Kontakte selbst, stellt ein, in welchen Standorten  und Fachbereichen sie sich zugehörig fühlen und wer, was sehen kann
* Freundschaftsbeziehungen (Freunde können gegenseitig sich ihre Kontakte sehen)
* Standorte- / Fachbereichs-Orga kann Kontakte in ihrem Bereich verwalten
* automatischer Kontaktexport
