### ISSUE TITLE
Konzept erarbeiten: Standorte und Autor*innen auf Seiten von MFNF sichtbar machen

### ISSUE THREAD

**Issue by kulla** [serlo/u_neue-standorte#54]

**Comment by jakobwes** [comment]
Bisherige Ideen vom Workshop in Münster (leider musste ich feststellen, dass ich vergessen hatte die Datei zu speichern und da mein Laptop gestern abgestürzt ist, ist das eine Übersicht aus dem Kopf):
- Nutzer*innenfeedback: in eigene Seite verlagern, von Startseite weg und/oder Verweis auf Serlo-Seite
- Aufruf: bleibt, sehr wichtig: Kontaktperson mit Photo: "Melde dich bei..."
- Titelbild zentral darüber (siehe Serlo-Informatik)
- Autor*innenbilder, Bilder von Treffen/Redaktionstagen
- Entwicklung von MFNF neu generieren, aktualisieren
- Seite: Unsere Mitwirkenden: Autor\*innenbilder, Autor\*innen geordnet nach Bearbeitungen, Links auf Standorte, Kontaktmöglichkeiten (!!!)
- Unter jedem Buch: ganz unten: Ansprechperson + Standorte und Autor*innen als Mitwirkende, zuständige Personen. Wo melden, wenn Interesse mitzuhelfen
- ...
