### ISSUE TITLE
Wie ist der Prozess der Standortgründung?

### ISSUE THREAD

**Issue by metzgaria** [serlo/u_neue-standorte#7]
-Schritte bei der Standortgründung (Hochschulgruppe, Unit,...)
-Kriterien: ab wann wird als Standort gezählt, wann zb nur Redaktionsstandort,...

**Comment by kulla** [comment]
Hier mal eine vorläufige Liste an Fragen, die ich mit diesem Task verbinde (arbeite gerade im Overview-Dokument diesen Punkt aus):

* Wie ist der Prozess der Standortgründung? (vereinfachte bzw. idealtypischer Prozess / in der Realität wird jede Standortgründung von diesem Prozess sicherlich abweichen... Die Beantwortung dieser Frage soll uns in der Unit Orientierung beim Standorteaufbau geben)
* Welche Entwicklungsstufen nimmt ein Standort dabei und wie sind diese gekennzeichnet?
* Was ist das Ziel in der Standorteentwicklung?

**Comment by OleGaertner** [comment]
für mich ist dieser Task auch eng verknüpft mit der Frage nach dem strategischen Hintergrund der Standortebildung -> also mit dem Task "Definition und Eindordnung von Standorten" https://github.com/serlo-org/u_neue-standorte/issues/33

**Comment by kulla** [comment]
@OleGaertner Neue Aufgaben bei der Standortegründung:

* Standort muss seine eigene Standorteseite gründen
* Wir müssen den neuen Standort auf https://de.serlo.org/kontakt eintragen
